### ISSUE TITLE
Equation 7 - Getting Error Message

### ISSUE THREAD

**Issue by gpitel** [OneSolver/onesolver#4]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/_cprequest.py", line 656, in respond
    response.body = self.handler()
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/lib/encoding.py", line 188, in __call__
    self.body = self.oldhandler(_args, *_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/_cpdispatch.py", line 34, in __call__
    return self.callable(_self.args, *_self.kwargs)
  File "server.py", line 190, in services
    result = funcHandle(*funcArgs)
  File "/var/web_server/apps/CloudMath/controller/Control.py", line 365, in variable_change_value
    equation.constraint_check(solution, desig, float(value), MATHRENDER)
  File "/var/web_server/apps/CloudMath/model/MathHertz.py", line 217, in constraint_check
    _, _, singleVarDesigMap, vistedEquations = variable_create_map(self)
  File "/var/web_server/apps/CloudMath/model/MathHertz.py", line 77, in variable_create_map
    if not(variableTemp.equation in equations):
AttributeError: 'Variable' object has no attribute 'equation'
# Steps to Repeat

Change Rho1 to 0.2

**Comment by gpitel** [comment]
This equation was experimental and left in.  Used to test remote equations, where line come from another design. I deactivated it until the kinks can be worked out.

**Comment by gpitel** [comment]
This equation was experimental and left in.  Used to test remote equations, where line come from another design. I deactivated it until the kinks can be worked out.
